RealisticVision:
  inference_config: "configs/inference/inference-v1.yaml"
  motion_module:
    - "models/Motion_Module/mm_sd_v15.ckpt"

  dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV20_v20.safetensors"
  lora_model_path: ""

  seed:           [9620]
  steps:          25
  guidance_scale: 7.5

  filter_params:
    method: 'butterworth'
    n: 4
    d_s: 0.25
    d_t: 0.25

  # filter_params:
  #   method: 'gaussian'
  #   d_s: 0.25
  #   d_t: 0.25

  prompt:
    - "shrek dancing on the beach"

  n_prompt:
    - "worst quality, low quality, nsfw, logo, watermark"

